/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppArchiveRouteImport } from './routes/_app.archive'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppServicesCodenameRouteImport } from './routes/_app.services.$codename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesCodenameRoute = AppServicesCodenameRouteImport.update({
  id: '/services/$codename',
  path: '/services/$codename',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/archive': typeof AppArchiveRoute
  '/health': typeof AppHealthRoute
  '/projects': typeof AppProjectsRoute
  '/tasks': typeof AppTasksRoute
  '/services/$codename': typeof AppServicesCodenameRoute
  '/services/': typeof AppServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/archive': typeof AppArchiveRoute
  '/health': typeof AppHealthRoute
  '/projects': typeof AppProjectsRoute
  '/tasks': typeof AppTasksRoute
  '/services/$codename': typeof AppServicesCodenameRoute
  '/services': typeof AppServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/services/$codename': typeof AppServicesCodenameRoute
  '/_app/services/': typeof AppServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/archive'
    | '/health'
    | '/projects'
    | '/tasks'
    | '/services/$codename'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/archive'
    | '/health'
    | '/projects'
    | '/tasks'
    | '/services/$codename'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/archive'
    | '/_app/health'
    | '/_app/projects'
    | '/_app/tasks'
    | '/_app/services/$codename'
    | '/_app/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$codename': {
      id: '/_app/services/$codename'
      path: '/services/$codename'
      fullPath: '/services/$codename'
      preLoaderRoute: typeof AppServicesCodenameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppHealthRoute: typeof AppHealthRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppServicesCodenameRoute: typeof AppServicesCodenameRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppHealthRoute: AppHealthRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTasksRoute: AppTasksRoute,
  AppServicesCodenameRoute: AppServicesCodenameRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
